- name: Increase open file limit
  shell: |
    echo "* hard nofile 64000" >> /etc/security/limits.conf
    echo "* soft nofile 64000" >> /etc/security/limits.conf
    echo "root hard nofile 64000" >> /etc/security/limits.conf
    echo "root soft nofile 64000" >> /etc/security/limits.conf

- name: Set mongodb uri
  shell: pritunl set-mongodb mongodb://localhost:27017/pritunl
  notify: Restart pritunl

- name: Retrieve pritunl password
  shell: pritunl default-password
  register: password

- name: Change server port
  shell: pritunl set app.server_port 8081

- debug: var=password.stdout_lines