- name: Add Apt Keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items: "{{ apt_keys }}"


- name: Add mongodb apt repository
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/{{ mongodb_version }} multiverse
    filename: "mongodb-org-{{ mongodb_version }}"
    state: present

- name: Add pritunl apt repository
  apt_repository:
    repo: deb http://repo.pritunl.com/stable/apt focal main
    filename: "pritunl"
    state: present

- name: Install tools
  apt:
    name:
    - pritunl
    - mongodb-org
    - wireguard
    - wireguard-tools
    state: present

- name: Enable pritunl and mongodb
  shell: |
    systemctl enable mongod pritunl

- name: Start pritunl and mongodb
  shell: |
    systemctl start mongod pritunl

- name: Disable ufw
  community.general.ufw:
    state: disabled
